<?php
// Configuration
$apiLoginUrl = "https://api.jadoodigital.com/api/v2.1/user/auth/login";
$apiRefreshUrl = "https://api.jadoodigital.com/api/v2.1/user/auth/refresh";
$inputFile = "playlist.m3u"; // Input playlist file
$outputFile = "out.m3u";     // Output playlist file
$folder = "Ferdos_Jadoo";
$tokenFile = "$folder/token.cache";

// Credentials
$username = "jadoo6000";
$password = "jadoo6000";
$domain = "af1dd86c3fb8448e87bb7770000c930c";

// Ensure token is valid or regenerate it
function getValidToken($apiLoginUrl, $apiRefreshUrl, $folder, $tokenFile, $username, $password, $domain) {
    if (!file_exists($tokenFile)) {
        return generateToken($apiLoginUrl, $folder, $tokenFile, $username, $password, $domain);
    }

    $refreshToken = file_get_contents($tokenFile);
    $response = reqGet($apiRefreshUrl, "Bearer $refreshToken");
    $data = json_decode($response, true);

    if (!isset($data['data']['access_token'])) {
        return generateToken($apiLoginUrl, $folder, $tokenFile, $username, $password, $domain);
    }

    return $data['data']['access_token'];
}

// Generate new token
function generateToken($apiLoginUrl, $folder, $tokenFile, $username, $password, $domain) {
    $loginData = [
        "username" => $username,
        "password" => $password,
        "domain"   => $domain,
    ];
    $response = reqPost($apiLoginUrl, $loginData);
    $data = json_decode($response, true);

    if (isset($data['data']['refresh_token'])) {
        $refreshToken = $data['data']['refresh_token'];

        if (!is_dir($folder)) {
            mkdir($folder, 0755, true);
        }

        file_put_contents($tokenFile, $refreshToken);
        return $data['data']['access_token'];
    }

    die("Error: Unable to generate token.");
}

// Process playlist
function processPlaylist($inputFile, $outputFile, $apiBaseUrl, $authToken) {
    if (!file_exists($inputFile)) {
        die("Error: Input playlist file not found.\n");
    }

    $inputLines = file($inputFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    $outputLines = [];

    foreach ($inputLines as $line) {
        if (strpos($line, "EXTINF") !== false) {
            preg_match('/tvg-name="([^"]+)" .*?tvg-logo="([^"]+)"/', $line, $matches);
            $channelName = $matches[1] ?? 'Unknown Channel';
            $logo = $matches[2] ?? '';
            $id = strtolower(str_replace(' ', '_', $channelName));

            $apiUrl = $apiBaseUrl . $id;
            $m3u8Link = fetchM3u8Link($apiUrl, $authToken);

            if ($m3u8Link) {
                $outputLines[] = "#EXTINF:-1 tvg-name=\"$channelName\" tvg-logo=\"$logo\" group-title=\"Jadoo Auto Playlist Generated by FREDFLIX\",$channelName";
                $outputLines[] = $m3u8Link;
            } else {
                echo "Warning: Failed to fetch m3u8 link for ID: $id\n";
            }
        }
    }

    file_put_contents($outputFile, implode("\n", $outputLines));
    echo "Updated playlist saved to $outputFile\n";
}

// Fetch m3u8 link
function fetchM3u8Link($url, $authToken) {
    $curl = curl_init();
    curl_setopt_array($curl, [
        CURLOPT_URL => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => [
            "Authorization: Bearer $authToken",
            "User-Agent: Mozilla/5.0",
        ],
    ]);
    $response = curl_exec($curl);
    curl_close($curl);

    $data = json_decode($response, true);
    return $data['url'] ?? null;
}

// HTTP POST request
function reqPost($url, $data) {
    $curl = curl_init();
    curl_setopt_array($curl, [
        CURLOPT_URL => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => json_encode($data),
        CURLOPT_HTTPHEADER => [
            "Content-Type: application/json",
            "User-Agent: Mozilla/5.0",
        ],
    ]);
    $result = curl_exec($curl);
    curl_close($curl);
    return $result;
}

// HTTP GET request
function reqGet($url, $authHeader) {
    $curl = curl_init();
    curl_setopt_array($curl, [
        CURLOPT_URL => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => [
            "Authorization: $authHeader",
        ],
    ]);
    $result = curl_exec($curl);
    curl_close($curl);
    return $result;
}

// Main execution loop
$apiBaseUrl = "https://api.jadoodigital.com/api/v2.1/user/channel/";

$authToken = getValidToken($apiLoginUrl, $apiRefreshUrl, $folder, $tokenFile, $username, $password, $domain);
processPlaylist($inputFile, $outputFile, $apiBaseUrl, $authToken);
?>
