import os
import time
import json
import requests

# Configuration
API_LOGIN_URL = "https://api.jadoodigital.com/api/v2.1/user/auth/login"
API_REFRESH_URL = "https://api.jadoodigital.com/api/v2.1/user/auth/refresh"
INPUT_FILE = "playlist.m3u"  # Input playlist file
OUTPUT_FILE = "api.m3u"      # Output playlist file
TOKEN_FILE = "token.cache"

USERNAME = "jadoo6000"
PASSWORD = "jadoo6000"
DOMAIN = "af1dd86c3fb8448e87bb7770000c930c"

# Ensure token is valid or regenerate it
def get_valid_token():
    if not os.path.exists(TOKEN_FILE):
        return generate_token()

    with open(TOKEN_FILE, "r") as f:
        refresh_token = f.read().strip()

    headers = {"Authorization": f"Bearer {refresh_token}"}
    response = requests.get(API_REFRESH_URL, headers=headers)
    data = response.json()

    if "data" in data and "access_token" in data["data"]:
        return data["data"]["access_token"]

    return generate_token()

# Generate a new token
def generate_token():
    payload = {
        "username": USERNAME,
        "password": PASSWORD,
        "domain": DOMAIN
    }

    response = requests.post(API_LOGIN_URL, json=payload)
    data = response.json()

    if "data" in data and "refresh_token" in data["data"]:
        refresh_token = data["data"]["refresh_token"]
        with open(TOKEN_FILE, "w") as f:
            f.write(refresh_token)

        return data["data"]["access_token"]

    raise Exception("Error: Unable to generate token.")

# Process playlist
def process_playlist(api_base_url, auth_token):
    if not os.path.exists(INPUT_FILE):
        raise FileNotFoundError(f"Input file {INPUT_FILE} not found.")

    with open(INPUT_FILE, "r") as f:
        input_lines = f.readlines()

    output_lines = []

    for line in input_lines:
        if line.startswith("#EXTINF"):
            # Extract channel name and logo
            channel_name = extract_attribute(line, "tvg-name")
            logo_url = extract_attribute(line, "tvg-logo")
            channel_name_cleaned = channel_name.lower().replace(" ", "_")

            # Fetch M3U8 link
            api_url = f"{api_base_url}{channel_name_cleaned}"
            m3u8_link = fetch_m3u8_link(api_url, auth_token)

            if m3u8_link:
                output_lines.append(f'#EXTINF:-1 tvg-name="{channel_name}" tvg-logo="{logo_url}" '
                                    f'group-title="Jadoo Auto Playlist Generated by FREDFLIX",{channel_name}')
                output_lines.append(m3u8_link)
            else:
                print(f"Warning: Failed to fetch M3U8 link for {channel_name_cleaned}.")

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(output_lines))

    print(f"Updated playlist saved to {OUTPUT_FILE}")

# Extract attribute value from EXTINF line
def extract_attribute(line, attribute):
    import re
    pattern = f'{attribute}="([^"]+)"'
    match = re.search(pattern, line)
    return match.group(1) if match else "Unknown"

# Fetch M3U8 link
def fetch_m3u8_link(url, auth_token):
    headers = {"Authorization": f"Bearer {auth_token}"}
    response = requests.get(url, headers=headers)
    data = response.json()

    return data.get("url")

# Main execution loop
def main():
    api_base_url = "https://api.jadoodigital.com/api/v2.1/user/channel/"

    while True:
        print("Fetching token...")
        auth_token = get_valid_token()

        print("Processing playlist...")
        process_playlist(api_base_url, auth_token)

        print("Waiting for 5 minutes...")
        time.sleep(300)  # Wait 5 minutes

if __name__ == "__main__":
    main()
