import os
import requests
from flask import Flask, jsonify

# Flask app
app = Flask(__name__)

# Vercel Environment Variables
USERNAME = os.getenv("USERNAME", "jadoo6000")
PASSWORD = os.getenv("PASSWORD", "jadoo6000")
DOMAIN = os.getenv("DOMAIN", "af1dd86c3fb8448e87bb7770000c930c")
API_LOGIN_URL = "https://api.jadoodigital.com/api/v2.1/user/auth/login"
API_REFRESH_URL = "https://api.jadoodigital.com/api/v2.1/user/auth/refresh"
BASE_URL = "https://edge01.iptv.digijadoo.net/live/"
INPUT_PLAYLIST = "playlist.m3u"  # Path to your playlist file
OUTPUT_PLAYLIST = "out.m3u"

# Function to login and get a refresh token
def get_refresh_token():
    payload = {
        "username": USERNAME,
        "password": PASSWORD,
        "domain": DOMAIN
    }
    response = requests.post(API_LOGIN_URL, json=payload)
    response_data = response.json()
    if "data" in response_data and "refresh_token" in response_data["data"]:
        return response_data["data"]["refresh_token"]
    else:
        raise Exception("Login failed. Refresh token not found.")

# Function to refresh access token
def refresh_access_token(refresh_token):
    headers = {"Authorization": f"Bearer {refresh_token}"}
    response = requests.get(API_REFRESH_URL, headers=headers)
    response_data = response.json()
    if "data" in response_data and "access_token" in response_data["data"]:
        return response_data["data"]["access_token"]
    else:
        raise Exception("Failed to refresh access token.")

# Function to process the playlist
def generate_playlist(access_token):
    with open(INPUT_PLAYLIST, "r") as file:
        lines = file.readlines()

    output_lines = [
        "#EXTM3U",
        "#EXTGRP:Jadoo Auto Playlist Generated by Fredflix",
    ]

    for i in range(len(lines)):
        line = lines[i]
        if line.startswith("#EXTINF"):
            channel_name = line.split('tvg-name="')[1].split('"')[0]
            logo_url = line.split('tvg-logo="')[1].split('"')[0]
            group_title = "Jadoo Auto Playlist"
            id_line = lines[i + 1]
            channel_id = id_line.split(BASE_URL)[1].split("/")[0]

            # Fetch the new m3u8 link
            channel_url = f"https://api.jadoodigital.com/api/v2.1/user/channel/{channel_id}"
            headers = {"Authorization": f"Bearer {access_token}"}
            response = requests.get(channel_url, headers=headers)
            channel_data = response.json()
            if "url" in channel_data:
                stream_url = channel_data["url"]
                output_lines.append(
                    f'#EXTINF:-1 tvg-name="{channel_name}" tvg-logo="{logo_url}" group-title="{group_title}",{channel_name}'
                )
                output_lines.append(stream_url)

    # Save the new playlist
    with open(OUTPUT_PLAYLIST, "w") as file:
        file.write("\n".join(output_lines))

@app.route("/")
def main():
    try:
        refresh_token = get_refresh_token()
        access_token = refresh_access_token(refresh_token)
        generate_playlist(access_token)
        return jsonify({"status": "success", "message": f"Playlist updated. Check {OUTPUT_PLAYLIST}."})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)})

if __name__ == "__main__":
    app.run()
